### ISSUE TITLE
any preview?

### ISSUE THREAD

**Issue by fukemy** [VikasJilla/progress_dialog#1]

**Comment by VikasJilla** [comment]
@fukemy this is how it looks

![progress_dialog](https://user-images.githubusercontent.com/11890238/60196836-afc6d480-985b-11e9-8c3e-b018473a9af7.jpg)

**Comment by fukemy** [comment]
thanks, i just notice as a person who looking for good UI lib, it will be better if you provide some previews in READ.ME ASAP

**Comment by VikasJilla** [comment]
> thanks, i just notice as a person who looking for good UI lib, it will be better if you provide some previews in READ.ME ASAP

yeah sure, thank you.
