### ISSUE TITLE
Decorator as input

### ISSUE THREAD

**Issue by javzzi** [VikasJilla/progress_dialog#2]
Hi, first of all, thanks for the plugin, is just what i was looking!
I would like to suggest in the method showProgressDialog to add another input for the decorator of the container of the CustomProgressDialog. I would like to change the color to a different of Colors.black, and also change the borderRadious. You could also allow to change the whole container to a new one, and leave the existing as default.

**Comment by Vikas-Jilla** [comment]
Thank you.

Yeah sure.

**Comment by VikasJilla** [comment]
Thank you.

Yeah sure, will provide an option.
