### ISSUE TITLE
Prevent the back button from being pressed

### ISSUE THREAD

**Issue by yusrenaltair** [VikasJilla/progress_dialog#3]
What a great, simple to use Package.
I need a function to prevent the back button from being pressed, because I use this dialog while synchronizing data and to prevent 
```
Unhandled Exception: Failed assertion: boolean expression must not be null
```
kind of error, because progress_dialog no longer exist in widget tree

For this reason I add the following line to my code.
I hope you can add this function, because maybe many people need it.
 Thanks.
``` @override
  Widget build(BuildContext context) {
    final DialogTheme dialogTheme = DialogTheme.of(context);
    //start from this line
    return WillPopScope(
        onWillPop: () => Future.value(false),
        child: AnimatedPadding(
  //to this line

**Comment by VikasJilla** [comment]
sure thank you for pointing out

**Comment by VikasJilla** [comment]
thank you its fixed now
